version: '3'
volumes:
  prometheus-data:
  mqtt_log-data:
  mqtt_config-data:
  mqtt_data:
networks:
  rasberry:

services:
  mqtt:
    image: fstehle/rpi-mosquitto
    container_name: rasberry-mqtt
    volumes:
      - "mqtt_log-data:/mqtt/log"
      - "mqtt_config-data:/mqtt/config:ro"
      - "mqtt_data:/mqtt/data/"
    ports:      
      - '1883:1883'
      - '9001:9001'
    networks:
      - rasberry

  prometheus:
    image: ajeetraina/prometheus-armv7
    container_name: prometheus
    volumes:
      - "prometheus-data:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    network_mode: "host"

  grafana:
    image: fg2it/grafana-armhf:v4.6.2
    container_name: rasberry-grafana
    networks:
      - rasberry
    ports:
      - 3000:3000
