version: '3'
volumes:
  graphite-data:

services:
  graphite:
    image: ennexa/graphite
    container_name: rasberry-graphite
    volumes:
      - "graphite-data:/opt/graphite/storage/whisper"
    networks:
      - rasberry

  grafana:
    image: grafana/grafana
    container_name: rasberry-grafana
    networks:
      - rasberry
    ports:
      - 3000:3000
