version: '3'
volumes:
  graphite-data:
networks:
  rasberry:

services:
  graphite:
    image: passy/rpi-docker-graphite-api 
    container_name: rasberry-graphite
    volumes:
      - "graphite-data:/opt/graphite/storage/whisper"
    ports:
      - '8080:8080'
    networks:
      - rasberry

  grafana:
    image: fg2it/grafana-armhf:v4.5.2
    container_name: rasberry-grafana
    networks:
      - rasberry
    ports:
      - 3000:3000
