version: '3'
volumes:
  graphite-data:
  mqtt_log-data:
  mqtt_config-data:
  mqtt_data:
networks:
  rasberry:

services:
  mqtt:
    image: fstehle/rpi-mosquitto
    container_name: rasberry-mqtt
    volumes:
      - "mqtt_log-data:/mqtt/log"
      - "mqtt_config-data:/mqtt/config:ro"
      - "mqtt_data:/mqtt/data/"
    ports:      
      - '1883:1883'
      - '9001:9001'
    networks:
      - rasberry

        #  graphite:
        #    image: passy/rpi-docker-graphite-api 
        #    container_name: rasberry-graphite
        #    volumes:
        #      - "graphite-data:/opt/graphite/storage/whisper"
        #    ports:
        #      - '8080:8080'
        #    networks:
        #      - rasberry

  grafana:
    image: fg2it/grafana-armhf:v4.5.2
    container_name: rasberry-grafana
    networks:
      - rasberry
    ports:
      - 3000:3000
